### ISSUE TITLE
直接引入yi.js，调用时提示 Uncaught ReferenceError: YI is not defined？

### ISSUE THREAD

**Issue by NewbMiao** [wy-ei/YI#1]
RT，怎么回事呢？必须要require引入么？

**Comment by w4096** [comment]
@NewbMiao 哦，webpack 配置文件给弄错了，重新打包了一下，已经好了

**Comment by NewbMiao** [comment]
@wy-ei 
`yi.js: Uncaught TypeError: Cannot read property 'getImageData' of undefined`

我是这样调用的，

```
var y=new YI(img);
    y.filter('mean').then(function(y){
        y.replace(img);
    });
```

this.ctx 好像设置有问题？

**Comment by w4096** [comment]
@NewbMiao 这里确实有点问题，因为 new YI 之后，需要加载图片，这个是异步过程。之前没有发现错误的原因是，我创建了 YI 对象后，在用户点击处理按钮的时候图片已经加载完成了，向你这样写，在调用 filter 的时候图片还没有加载完成，所以给报错了。我对这里进行了一些处理现在应该好了。

**Comment by NewbMiao** [comment]
恩，现在是ok的
